# Generated by Django 3.1.2 on 2020-10-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grams', '0005_auto_20201001_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='BEE1ZwlYS7m3ZwDWy8Je', max_length=20),
        ),
    ]
