# Generated by Django 3.1.2 on 2020-10-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grams', '0006_auto_20201002_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tile',
        ),
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
        migrations.AddField(
            model_name='game',
            name='remaining_tiles',
            field=models.CharField(default='PHALRZSTIOBYETUBAIEUOJAMWDHGENUEAWOOUEEIAIDFXHRXKJANMAEEALEULBCFTDIEGATEGLSSCPSEVDNGERAITTQONARIREEVCOLOOSOROKQIORYENUNDZNIAWVFIARPEMTISTNTDRIYE', max_length=144),
        ),
        migrations.AddField(
            model_name='player',
            name='grid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rack',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AlterField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='OHqt8sfBRxo7k8QIHkMG', max_length=20),
        ),
    ]
