# Generated by Django 3.1.2 on 2020-10-02 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grams', '0007_auto_20201002_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='remaining_tiles',
            field=models.CharField(default='USADUUIBTQTTNUEPTDROOJEFDTGIBOKPXAEOOITNCIHRLMOHNSEAFAVELMGAOYSGTEAQYUALRIIEWIRIINREGEUEZRHNWBEOOTDILYEAZILVOMSSPCIANWTRNNAEREESOEVJAEECXKAFDRDA', max_length=144),
        ),
        migrations.AlterField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='iMOFTkJpQPRHdCMYE0iZ', max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grams.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grams.player')),
            ],
        ),
    ]
