# Generated by Django 3.1.2 on 2020-10-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='game_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='active_game',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
