# Generated by Django 3.1.2 on 2020-10-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201001_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='active_game',
            new_name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='9t0SM5tx4DgkpQA4Gik5', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
