# Generated by Django 3.1.2 on 2020-10-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201001_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='zCamcdvqjtT2HtD69ZrL', max_length=20),
        ),
    ]
