# Generated by Django 3.1.2 on 2020-10-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201002_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='remaining_tiles',
            field=models.CharField(default='XPRMCWEGAKVAFLNTEEARBEUSAEDIGOZORZOOEAUTEHAEHSDNIUTCEYCIEBATDOOEIMYPAASLNUNAEGEROVDLESDAFKAWLIORFOORITQVIIPBHGNNTUSMLOJRNSRTQYTDXAEIJRIENWIEEUIT', max_length=144),
        ),
        migrations.AlterField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='1u7bM6VzbX7Y2dKuxHge', max_length=20),
        ),
    ]
