# Generated by Django 3.1.2 on 2020-10-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201002_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='remaining_tiles',
            field=models.CharField(default='AQAHWIZMNCTGLMINXETBITETUEYOROIDAAUDTEANVKEVHWDTRASOELREIQEVOIAATOAURSUYTNEEJWRRINGELEFDIESIOYSESTANPUBPPCJGEGOKIZMDAIOBLSRAEOAXFLRNOENFCIERDOUH', max_length=144),
        ),
        migrations.AlterField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='tIwV2F6cLMNV0Ta9ZWOJ', max_length=20),
        ),
    ]
