# Generated by Django 3.1.2 on 2020-10-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20201002_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='player',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('START', 'START'), ('JOIN', 'JOIN'), ('PEEL', 'PEEL'), ('DUMP', 'DUMP'), ('BANANAS', 'BANANAS'), ('WIN', 'WIN'), ('ROTTEN', 'ROTTEN')], default='CREATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='remaining_tiles',
            field=models.CharField(default='OIOTIIIANDTRWAYLLTRIDTERENNKACEUAREOEEDNMOHFTAZIQAGCYIOESESPNHWERRZSOLGIITNALABEOUAXSGRIPOONAUREGHNJMTCMDFVBSQUAKTLRXEBPWEJSEUADEOYVITEFOEIDVEAU', max_length=144),
        ),
        migrations.AlterField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='PNdqcdhTt4hLN08K7jVO', max_length=20),
        ),
    ]
