# Generated by Django 3.1.2 on 2020-10-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20201003_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='remaining_tiles',
            field=models.CharField(default='PRSUJABBONLSOEEHYUHCEONGZNNLIAUOQGEBMRERANDIADTIDVRNLIVIEFJTEITEAETWLTTFEILSZRAQRNCTPUADIWXRUGHEAORYAGOCOOSORDKETSTDAMKIXEIFEEUESAVYWONEMAIIOPAE', max_length=144),
        ),
        migrations.AlterField(
            model_name='game',
            name='url_key',
            field=models.CharField(default='nJshjB7r5XMFHq1LUK7R', max_length=20),
        ),
    ]
