# Generated by Django 3.1.2 on 2020-10-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20201003_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='url_key',
        ),
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='remaining_tiles',
            field=models.CharField(default='AAOELTAEIOTHIJAKJGQIGDUHAUEGBEZZWEWIEWFIULDDMREXALERVTTNOOOEKUTNULEASOEAOSRTACRIQETEUCIYYPETSOEEERGNDFNLDEIMNMIRROAANTAVRPBVDCIYSRIBSNXAONOHSPIF', max_length=144),
        ),
    ]
