# Generated by Django 3.1.2 on 2020-10-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20201003_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_url',
            new_name='url_key',
        ),
        migrations.AlterField(
            model_name='game',
            name='remaining_tiles',
            field=models.CharField(default='UROHAFIOQSCWOEATDENOLIEYRERLXGINBLEREENREITSUIFRCIEAWAQJEOEXHAOAAFNAITTENPJBSODOIZKRMUAVNTGDUTNEEBUDOTMRYYPWCHSASASIOEZGILIEEVPUEVARIMATODKTLNDG', max_length=144),
        ),
    ]
